/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CareTakerWorkArea;

import Healthplus.E_System;
import Healthplus.SeniorMedical.SeniorMedical;
import Healthplus.Enterprises.Enterprise;
import Healthplus.SeniorCare.SeniorCare;
import Healthplus.Org.MedicalOrg;
import Healthplus.Org.Org;
import Healthplus.UserAccount.UserAccount;
import Healthplus.WorkQueue.SeniorMedicalWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class SendSeniorForTreatmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SendSeniorForTreatmentJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Org organization;
    private Enterprise enterprise;
    private E_System system;
    
    public SendSeniorForTreatmentJPanel(JPanel userProcessContainer, E_System system, UserAccount userAccount, Org organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        populateViewCoordinatorTable();
    }
    
    public void populateViewCoordinatorTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblViewCoordinators.getModel();

        model.setRowCount(0);
                for (SeniorCare senior : enterprise.getSeniorCareDirectory().getSeniorCareList()) {
                    Object[] row = new Object[2];
                    row[0] = senior;
                    row[1] = senior.isIllness();
                    model.addRow(row);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_goback = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCoordinators = new javax.swing.JTable();
        btn_goTreat = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btn_goback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-button.png"))); // NOI18N
        btn_goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gobackActionPerformed(evt);
            }
        });

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Send Seniors for Treatment");

        tblViewCoordinators.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Illness"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewCoordinators);

        btn_goTreat.setBackground(new java.awt.Color(113, 160, 160));
        btn_goTreat.setText("Send for Treatment");
        btn_goTreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goTreatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(btn_goTreat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_goback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_goTreat)
                .addGap(157, 157, 157)
                .addComponent(btn_goback, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gobackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_gobackActionPerformed

    private void btn_goTreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goTreatActionPerformed
        int selectedRow = tblViewCoordinators.getSelectedRow();
        if (selectedRow >= 0) {
            SeniorCare senior = (SeniorCare) tblViewCoordinators.getValueAt(selectedRow, 0);
            String name = senior.getName();
            boolean illness = senior.isIllness();

            if(senior.isIllness() == true){
                enterprise.getSeniorCareDirectory().removeSeniorCare(senior);
                populateViewCoordinatorTable();

                SeniorMedicalWorkRequest req = new SeniorMedicalWorkRequest();
                SeniorMedical seniors = new SeniorMedical();
                seniors.setName(name);
                seniors.setIllness(illness);
                seniors.setStatus(true);
                req.setSenior(seniors);

                for(Org organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof MedicalOrg) {
                        organization.getWorkQueue().getWorkRequestList().add(req);
                    }
                }

                JOptionPane.showMessageDialog(null, "Request successfully sent to Medical", "Information", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Only Seniors with illness can be sent for Treatment", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_goTreatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_goTreat;
    private javax.swing.JButton btn_goback;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable tblViewCoordinators;
    // End of variables declaration//GEN-END:variables
}
